dist: bionic
language: java
before_install:
- rm ~/.m2/settings.xml
jdk:
- openjdk11
install: ./mvnw -v
script: ./mvnw -B -nsu verify jacoco:report
cache:
  directories:
  - "$HOME/.m2"
branches:
  except:
  - "/^release\\/.*$/"
  - "/^feature\\/.*$/"
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: vp/xXQkh6jExSu2+Yf1l7+0+AhmQpYpa/HaAIgOSjDbvjTs/CjoK2+or/ITR9ECcz86u1rNEhAK0rOcrbraNTCUsxQGK/U2asLJJ1HXMFD+aYcl7bPnQza7/ufbppHSS9jD7odDNC11PBxv3hNBsxv5Dyf1uy8439Q/HlGBr2jP8JQsloWEPM4ffzbeobADtVmvF/qde4F2J1+SnSwH6SJxzNjGFwsg9nkOQO+x0c6KcS/8U/R9yneEvhkTQFQlcAF62YIl8JYVkjZEZPMccyx74RUcWLHqBBeoLJ2Vqo/ml9BL3ZvZd/KryqxUafuc5e/VxzCtEGno4tq32zNKK0ny+tMbNAa0T1JMyFkCN4c4QpKyMIrErvVzEZ49MYdaED3M9jqMUJlFC7m6eENRQrcUQ6rM5O25xxVPziQC5fw41M8OipunUJsPs3Q94gh0YaAYyOiZDUVQ6zvKKybZ6Gldjm+xxetgkCaLwxl7N9SrQZ60vf3KRd+3WqTBVPeC0hOuguWPXNcb2SGJPbANZdjubTF9YixEWWSFmF7tSEJM9tcvR68YLlvKscMwhHgZl6qJ5wb5c3r4OPicbF9wU8464kv9qH4nqn+W0cperMyd0npENdbG/eqajJvEWgc8vXHzEPYedJPUpDAN5lc8VDiLHzglzEDhWZJLngIDlzak=
